cartant/eslint-plugin-rxjs

source/rules/no-compat.ts, tests/rules/no-compat.ts
TSLint:
- https://github.com/cartant/rxjs-tslint-rules/blob/master/source/rules/rxjsNoCompatRule.ts
- https://github.com/cartant/rxjs-tslint-rules/blob/master/test/v6/fixtures/no-compat/default/fixture.ts.lint
=> feat: add no-compat

source/rules/no-explicit-generics.ts, tests/rules/no-explicit-generics.ts
TSLint:
- https://github.com/cartant/rxjs-tslint-rules/blob/master/source/rules/rxjsNoExplicitGenericsRule.ts
- https://github.com/cartant/rxjs-tslint-rules/blob/master/test/v6/fixtures/no-explicit-generics/default/fixture.ts.lint
=> feat: add no-explicit-generics

source/rules/no-ignored-subscribe.ts, source/rules/no-ignored-subscription.ts, tests/rules/no-ignored-subscription.ts
Part of #1 
TSLint:
- https://github.com/cartant/rxjs-tslint-rules/blob/master/source/rules/rxjsNoIgnoredSubscriptionRule.ts
- https://github.com/cartant/rxjs-tslint-rules/blob/master/test/v6/fixtures/no-ignored-subscription/default/fixture.ts.lint
=> feat: add no-ignored-subscription

source/rules/no-ignored-observable.ts, tests/rules/no-ignored-observable.ts
Part of #1 
TSLint:
- https://github.com/cartant/rxjs-tslint-rules/blob/master/source/rules/rxjsNoIgnoredObservableRule.ts
- https://github.com/cartant/rxjs-tslint-rules/blob/master/test/v6/fixtures/no-ignored-observable/default/fixture.ts.lint
=> feat: add no-ignored-observable

source/rules/no-async-subscribe.ts, tests/rules/no-async-subscribe.ts
Part of #1 
TSLint:
- https://github.com/cartant/rxjs-tslint-rules/blob/master/source/rules/rxjsNoAsyncSubscribeRule.ts
- https://github.com/cartant/rxjs-tslint-rules/blob/master/test/v6/fixtures/no-async-subscribe/default/fixture.ts.lint
=> feat: add no-async-subscribe

@types/esquery/index.d.ts, source/rules/no-nested-subscribe.ts, source/utils.ts, tests/rules/no-nested-subscribe.ts
Part of #1 
TSLint:
- https://github.com/cartant/rxjs-tslint-rules/blob/master/source/rules/rxjsNoNestedSubscribeRule.ts
- https://github.com/cartant/rxjs-tslint-rules/blob/master/test/v6/fixtures/no-nested-subscribe/default/fixture.ts.lint
- https://github.com/cartant/rxjs-tslint-rules/blob/master/test/v6/fixtures/no-nested-subscribe/prototype/fixture.ts.lint
=> feat: add no-nested-subscribe

source/rules/no-subject-value.ts, tests/rules/no-subject-value.ts
Part of #1 
TSLint:
- https://github.com/cartant/rxjs-tslint-rules/blob/master/source/rules/rxjsNoSubjectValueRule.ts
- https://github.com/cartant/rxjs-tslint-rules/blob/master/test/v6/fixtures/no-subject-value/default/fixture.ts.lint
=> feat: add no-subject-value

source/rules/no-ignored-replay-buffer.ts, tests/rules/no-ignored-replay-buffer.ts
Part of #1 
TSLint:
- https://github.com/cartant/rxjs-tslint-rules/blob/master/source/rules/rxjsNoIgnoredReplayBufferRule.ts
- https://github.com/cartant/rxjs-tslint-rules/blob/master/test/v6/fixtures/no-ignored-replay-buffer/default/fixture.ts.lint
- https://github.com/cartant/rxjs-tslint-rules/blob/master/test/v6/fixtures/no-ignored-replay-buffer/diff-import-alias/fixture.ts.lint
=> feat: add no-ignored-replay-buffer

source/rules/no-exposed-subjects.ts, tests/rules/no-exposed-subjects.ts
Part of #1 
TSLint:
- https://github.com/cartant/rxjs-tslint-rules/blob/master/source/rules/rxjsNoExposedSubjectsRule.ts
- https://github.com/cartant/rxjs-tslint-rules/blob/master/test/v6/fixtures/no-exposed-subjects/angular/fixture.ts.lint
- https://github.com/cartant/rxjs-tslint-rules/blob/master/test/v6/fixtures/no-exposed-subjects/default/fixture.ts.lint
- https://github.com/cartant/rxjs-tslint-rules/blob/master/test/v6/fixtures/no-exposed-subjects/protected/fixture.ts.lint
- https://github.com/cartant/rxjs-tslint-rules/blob/master/test/v6/fixtures/no-exposed-subjects/protected-angular/fixture.ts.lint
=> feat: add no-exposed-subjects

source/rules/no-subject-unsubscribe.ts, tests/rules/no-subject-unsubscribe.ts
Part of #1
TSLint:
- https://github.com/cartant/rxjs-tslint-rules/blob/master/source/rules/rxjsNoSubjectUnsubscribeRule.ts
- https://github.com/cartant/rxjs-tslint-rules/blob/master/test/v6/fixtures/no-subject-unsubscribe/subject/fixture.ts.lint
- https://github.com/cartant/rxjs-tslint-rules/blob/master/test/v6/fixtures/no-subject-unsubscribe/async-subject/fixture.ts.lint
=> feat: add no-subject-unsubscribe

source/rules/no-async-subscribe.ts, source/rules/no-connectable.ts, source/rules/no-exposed-subjects.ts, source/rules/no-ignored-observable.ts, source/rules/no-ignored-subscribe.ts, source/rules/no-ignored-subscription.ts, source/rules/no-nested-subscribe.ts, source/rules/no-subject-unsubscribe.ts, source/rules/no-subject-value.ts, source/rules/no-unbound-methods.ts, source/rules/throw-error.ts, source/utils.ts
This PR adds some helper functions for the `couldBeYYY` functions.
=> refactor: helper functions

source/rules/no-async-subscribe.ts, source/rules/no-exposed-subjects.ts, source/rules/no-tap.ts, tests/rules/no-tap.ts
TSLint:
- https://github.com/cartant/rxjs-tslint-rules/blob/master/source/rules/rxjsNoTapRule.ts
- https://github.com/cartant/rxjs-tslint-rules/blob/master/test/v6/fixtures/no-tap/default/fixture.ts.lint
=> feat: add no-tap

package.json, source/rules/no-unsafe-first.ts, source/utils.ts, tests/rules/no-unsafe-first.ts
Part of #1
TSLint:
- https://github.com/cartant/rxjs-tslint-rules/blob/master/source/rules/rxjsNoUnsafeFirstRule.ts
- https://github.com/cartant/rxjs-tslint-rules/blob/master/test/v6/fixtures/no-unsafe-first/default/fixture.ts.lint
=> feat: add no-unsafe-first

package.json, source/rules/no-unsafe-takeuntil.ts, source/utils.ts, tests/rules/no-unsafe-takeuntil.ts
Part of #1 
I don't know why but it feels like I missed something here...
TSLint:
- https://github.com/cartant/rxjs-tslint-rules/blob/master/source/rules/rxjsNoUnsafeTakeuntilRule.ts
- https://github.com/cartant/rxjs-tslint-rules/blob/master/test/v6/fixtures/no-unsafe-takeuntil/default/fixture.ts.lint
- https://github.com/cartant/rxjs-tslint-rules/blob/master/test/v6/fixtures/no-unsafe-takeuntil/allow-custom/fixture.ts.lint
- https://github.com/cartant/rxjs-tslint-rules/blob/master/test/v6/fixtures/no-unsafe-takeuntil/allow-default/fixture.ts.lint
=> feat: add no-unsafe-takeuntil

package.json, source/rules/no-unsafe-catch.ts, source/utils.ts, tests/rules/no-unsafe-catch.ts
Part of #1 
TSLint:
- https://github.com/cartant/rxjs-tslint-rules/blob/master/source/rules/rxjsNoUnsafeCatchRule.ts
- https://github.com/cartant/rxjs-tslint-rules/blob/master/test/v6/fixtures/no-unsafe-catch/default/fixture.ts.lint
- https://github.com/cartant/rxjs-tslint-rules/blob/master/test/v6/fixtures/no-unsafe-catch/resubscribe/fixture.ts.lint
=> feat: add no-unsafe-catch

source/rules/ban-observables.ts, tests/rules/ban-observables.ts
Part of #1 
TSLint:
- https://github.com/cartant/rxjs-tslint-rules/blob/master/source/rules/rxjsBanObservablesRule.ts
- https://github.com/cartant/rxjs-tslint-rules/blob/master/test/v6/fixtures/ban-observables/default/fixture.ts.lint
=> feat: add ban-observables

source/rules/ban-operators.ts, tests/rules/ban-operators.ts
Part of #1 
TSLint:
- https://github.com/cartant/rxjs-tslint-rules/blob/master/source/rules/rxjsBanOperatorsRule.ts
- https://github.com/cartant/rxjs-tslint-rules/blob/master/test/v6/fixtures/ban-operators/default/fixture.ts.lint
=> feat: add ban-operators

source/rules/no-create.ts, tests/rules/no-create.ts
TSLint:
- https://github.com/cartant/rxjs-tslint-rules/blob/master/source/rules/rxjsNoCreateRule.ts
- https://github.com/cartant/rxjs-tslint-rules/blob/master/test/v6/fixtures/no-create/default/fixture.ts.lint
=> feat: add no-create

source/rules/no-ignored-error.ts, source/utils.ts, tests/rules/no-ignored-error.ts
TSLint:
- https://github.com/cartant/rxjs-tslint-rules/blob/master/source/rules/rxjsNoIgnoredErrorRule.ts
- https://github.com/cartant/rxjs-tslint-rules/blob/master/test/v6/fixtures/no-ignored-error/default/fixture.ts.lint
=> feat: add no-ignored-error

source/rules/no-ignored-notifier.ts, source/utils.ts, tests/rules/no-ignored-notifier.ts
TSLint:
- https://github.com/cartant/rxjs-tslint-rules/blob/master/source/rules/rxjsNoIgnoredNotifierRule.ts
- https://github.com/cartant/rxjs-tslint-rules/blob/master/test/v6/fixtures/no-ignored-notifier/default/fixture.ts.lint
=> feat: add no-ignored-notifier

source/rules/no-subclass.ts, source/utils.ts, tests/rules/no-subclass.ts
TSLint:
- https://github.com/cartant/rxjs-tslint-rules/blob/master/source/rules/rxjsNoSubclassRule.ts
- https://github.com/cartant/rxjs-tslint-rules/blob/master/test/v6/fixtures/no-subclass/default/fixture.ts.lint
=> feat: add no-subclass

package.json, source/rules/no-unsafe-catch.ts, source/rules/no-unsafe-first.ts, source/rules/no-unsafe-switchmap.ts, source/utils.ts, tests/rules/no-unsafe-switchmap.ts, tests/utils-spec.ts, yarn.lock
Part of #1 
TSLint:
- https://github.com/cartant/rxjs-tslint-rules/blob/master/source/rules/rxjsNoUnsafeSwitchmapRule.ts
- https://github.com/cartant/rxjs-tslint-rules/blob/master/test/v6/fixtures/no-unsafe-switchmap/default/fixture.ts.lint
- https://github.com/cartant/rxjs-tslint-rules/blob/master/test/v6/fixtures/no-unsafe-switchmap/allow-foo/fixture.ts.lint
- https://github.com/cartant/rxjs-tslint-rules/blob/master/test/v6/fixtures/no-unsafe-switchmap/disallow-foo/fixture.ts.lint
=> feat: add no-unsafe-switchmap

source/rules/no-finnish.ts, tests/rules/no-finnish.ts
Converting RxJS no-finnish notation in tslint to eslint #7
=> feat: add no-finnish (#7)

source/rules/just.ts, tests/rules/just.ts
**This PR does not provide an auto-fix.**
TSLint:
- https://github.com/cartant/rxjs-tslint-rules/blob/master/source/rules/rxjsJustRule.ts
- https://github.com/cartant/rxjs-tslint-rules/blob/master/test/v6/fixtures/just/user-land/fixture.ts.lint
- https://github.com/cartant/rxjs-tslint-rules/blob/master/test/v6/fixtures/just/default/fixture.ts.lint
=> [WIP] feat: add just

package.json, tsconfig.json
=> chore: support node 10 engine and downlevel to es2018
